dist: xenial

language: generic

env:
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11

os:
  - freebsd
  - linux
  - osx

jobs:
  include:
  - os: linux
    env: OCAML_VERSION=4.11 INSTALL_LOCAL=1

cache:
  directories:
    - $HOME/.opam
    - $HOME/.rvm

addons:
  apt:
    packages:
      - autoconf
      - autotools-dev
      - libtool
      - pkg-config
      - libffi-dev
      - ruby-full
      - ruby-bundler
  homebrew:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - libffi
      - ruby
      - ruby-build

before_install:
  # INSTALL WEB SERVER DEPS
  - gem install -v 0.9.0 childprocess 
  - gem install -v 2.0.5 sinatra
  - gem install -v 2.0.5 sinatra-contrib
  - gem install -v 1.7.2 thin

  # INSTALL OPAM
  - test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh  

  # INSTALL DEPS
  - opam install -y ocamlfind ocamlbuild num zarith extunix lem

  # INSTALL DASH
  - (cd libdash; opam pin -y add .)

install:
  # BUILD SMOOSH
  - opam exec -- make -C src all all.byte
  - export PATH="$(pwd)/src:$PATH"
  
script:
  # TEST SMOOSH
  - make -C src/ test
  - TEST_DEBUG=1 TEST_TIMEOUT=15 make -C tests/ test # higher timeout for CI (default is 9s)

  # RUN MODERNISH TESTS (WHICH WILL HAVE SOME FAILURES WITH DASH'S PARSER)
  - yes n | modernish/install.sh -s smoosh 2>&1 | tee modernish.log || true
  - test "$(grep BUG modernish.log)" = '   LOCALVARS TRAPPRSUBSH BUG_MULTIBYTE' || echo "Expected BUG_MULTIBYTE (and no others)"
  - test "$(grep FAIL modernish.log | cut -c3,4,5)" = '002' || echo 'Expected ASCII char failure'
  
  # BUILD AND TEST WEB SERVER
  - (cd web; bundle install)
  - sh web/src/mk_config.sh $(pwd) >web/src/config.yml
  - cat web/src/config.yml
  - mkdir web/submissions
  - pwd
  - web/run.sh &
  - sleep 5
  - curl --fail --data-ascii @web/test.post http://localhost:2080/shtepper
