FROM smoosh

# fragile!
# OCaml base image isn't up-to-date enough to install ruby---need deb9u3!
# at least we're doing the update AFTER having built smoosh :(
RUN sudo apt-get update
RUN sudo apt-get install -y ruby-full ruby-bundler
RUN sudo gem install childprocess sinatra sinatra-contrib thin

ADD --chown=opam:opam web web
RUN cd web; bundle install
RUN mv web/src/config.yml.docker web/src/config.yml
RUN mkdir web/submissions

EXPOSE 2080/tcp
#EXPOSE 2443/tcp

#ENTRYPOINT [ "opam", "config", "exec", "--" ]
CMD /home/opam/web/run.sh
