(* Generated by Lem from version.lem. *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import String.
Require Import Program.Wf.

Require Import coqharness.

Open Scope nat_scope.
Open Scope string_scope.

Require Import lem_pervasives_extra.
Require Export lem_pervasives_extra.

(* [?]: removed value specification. *)

Definition smoosh_version   : string :=  "0.1".
(* [?]: removed value specification. *)

Definition smoosh_build   : string :=  "2019-09-06_20:56".
(* [?]: removed value specification. *)

Definition smoosh_info   : string :=   String.append"smoosh v"  (String.append smoosh_version  (String.append" (build "  (String.append smoosh_build ")
"))).
